### ISSUE TITLE
Doesn't compile as you say

### ISSUE THREAD

**Issue by cpmachado** [jtvaughan/simplelexer#1]
Enough said, I'm a noob.
I was having trouble compiling, because of your fancy int_fast8_t weren't defined according to gcc.
Using gcc, you need to include stdint for the type definition of this.
I don't know about the standard.
Thanks for your attention.
Btw. Big fan, you made my afternoon checking your repos, because of ptar. Love the attitude.

**Comment by jtvaughan** [comment]
No, you're absolutely right.  I just fixed the problem in master: Please give it another try.

Thanks for pointing this out!  And I'm glad you enjoy my code, though I haven't been active on GitHub lately.

**Comment by cpmachado** [comment]
All good, was browsing the interwebs, passing through the suckless "other projects", noticed oboeta. Checked your repo, and then the others, there's an sltar project you might find interesting to look at their page.
I used to code lots of C, so C code was what I was into checking, noticed ptar and this lexer. You good.
All is good.

**Comment by cpmachado** [comment]
j
